//
// Generated file, do not edit! Created by opp_msgtool 6.3 from src/Packet.msg.
//

#ifndef __PACKET_M_H
#define __PACKET_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// opp_msgtool version check
#define MSGC_VERSION 0x0603
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgtool: 'make clean' should help.
#endif

class IoTPacket;
/**
 * Class generated from <tt>src/Packet.msg:2</tt> by opp_msgtool.
 * <pre>
 * packet IoTPacket
 * {
 *     string sourceId;
 *     string destinationId;
 *     int sequenceNumber;
 *     simtime_t timestamp;
 *     double temperatureValue;
 *     string nonce;
 *     int payloadSize;
 *     string encryptionAlgorithm;
 *     string authenticationTag;
 *     bool isEncrypted;
 *     bool isTampered;
 *     bool isReplay;
 *     bool isAccepted;
 *     string attackType;
 * }
 * </pre>
 */
class IoTPacket : public ::omnetpp::cPacket
{
  protected:
    omnetpp::opp_string sourceId;
    omnetpp::opp_string destinationId;
    int sequenceNumber = 0;
    omnetpp::simtime_t timestamp = SIMTIME_ZERO;
    double temperatureValue = 0;
    omnetpp::opp_string nonce;
    int payloadSize = 0;
    omnetpp::opp_string encryptionAlgorithm;
    omnetpp::opp_string authenticationTag;
    bool isEncrypted_ = false;
    bool isTampered_ = false;
    bool isReplay_ = false;
    bool isAccepted_ = false;
    omnetpp::opp_string attackType;

  private:
    void copy(const IoTPacket& other);

  protected:
    bool operator==(const IoTPacket&) = delete;

  public:
    IoTPacket(const char *name=nullptr, short kind=0);
    IoTPacket(const IoTPacket& other);
    virtual ~IoTPacket();
    IoTPacket& operator=(const IoTPacket& other);
    virtual IoTPacket *dup() const override {return new IoTPacket(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    virtual const char * getSourceId() const;
    virtual void setSourceId(const char * sourceId);

    virtual const char * getDestinationId() const;
    virtual void setDestinationId(const char * destinationId);

    virtual int getSequenceNumber() const;
    virtual void setSequenceNumber(int sequenceNumber);

    virtual omnetpp::simtime_t getTimestamp() const;
    virtual void setTimestamp(omnetpp::simtime_t timestamp);

    virtual double getTemperatureValue() const;
    virtual void setTemperatureValue(double temperatureValue);

    virtual const char * getNonce() const;
    virtual void setNonce(const char * nonce);

    virtual int getPayloadSize() const;
    virtual void setPayloadSize(int payloadSize);

    virtual const char * getEncryptionAlgorithm() const;
    virtual void setEncryptionAlgorithm(const char * encryptionAlgorithm);

    virtual const char * getAuthenticationTag() const;
    virtual void setAuthenticationTag(const char * authenticationTag);

    virtual bool isEncrypted() const;
    virtual void setIsEncrypted(bool isEncrypted);

    virtual bool isTampered() const;
    virtual void setIsTampered(bool isTampered);

    virtual bool isReplay() const;
    virtual void setIsReplay(bool isReplay);

    virtual bool isAccepted() const;
    virtual void setIsAccepted(bool isAccepted);

    virtual const char * getAttackType() const;
    virtual void setAttackType(const char * attackType);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const IoTPacket& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, IoTPacket& obj) {obj.parsimUnpack(b);}


namespace omnetpp {

template<> inline IoTPacket *fromAnyPtr(any_ptr ptr) { return check_and_cast<IoTPacket*>(ptr.get<cObject>()); }

}  // namespace omnetpp

#endif // ifndef __PACKET_M_H

